cache:
  paths:
  - node_modules/

stages:
  - lint
  - deploy

eslint:
  stage: lint
  script:
    - npm i
    - npm run lint
  tags:
    - pp-projects

build_dev:
  stage: deploy
  script:
    - cd /home/devuser/DevProjects/656.echo_explorer/explorer
    - git pull
    - npm i
    - npm link echojs-lib
    - npm run build-dev
  only:
    - development
  environment:
    name: development
  tags:
    - pp-projects
