stages:
  - test
  - build

eslint:
  image: node:10.15
  stage: test
  cache:
    key: $CI_COMMIT_REF_NAME
    paths:
    - node_modules/
  script:
    # TODO: only for support private lib
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

    - npm i --silent
    - npm run lint
  tags:
    - master

build.master:
  stage: build
  cache:
    key: $CI_COMMIT_REF_NAME
    paths:
      - node_modules
  script:
    - if [ -d node_modules/echojs-lib ]; then rm -rf node_modules/echojs-lib; fi
    - npm config set unsafe-perm true
    - npm i
    - npm run build-stage
    - rm -rf /home/frontend
    - cp -r ./dist /home/frontend
  only:
    - master
  tags:
    - master
  environment:
    name: stage

build.develop:
  stage: build
  cache:
    key: $CI_COMMIT_REF_NAME
    paths:
      - node_modules
  script:
    - if [ -d node_modules/echojs-lib ]; then rm -rf node_modules/echojs-lib; fi
    - npm config set unsafe-perm true
    - npm i
    - npm run build-dev
    - rm -rf /home/frontend
    - cp -r ./dist /home/frontend
  only:
    - develop
  tags:
    - develop
  environment:
    name: development

build.production:
  stage: build
  variables:
    NODE_ENV: "production"
  script:
    - NODE_ENV=development npm i
    - npm run build
    - rm -rf /var/www/testnet.explorer.echo-dev.io/*
    - cp -r ./dist/* /var/www/testnet.explorer.echo-dev.io
  only:
    - tags
  tags:
    - echo-linux
  environment:
    name: production
    url: https://testnet.explorer.echo-dev.io
