stages:
  - test
  - build
  - deploy

include:
  - project: 'service/devops'
    ref: master
    file: 'build/frontend/.gitlab-ci.yml'  

lint:
  image: node:10.15
  stage: test
  cache:
    key: $CI_COMMIT_REF_NAME
    paths:
      - node_modules/
  script:
    - npm i --silent
    - npm run lint
  only:
    - merge_requests
  tags:
    - docker

.deploy:
  stage: deploy
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker-compose pull
    - docker-compose -p 656-echo-explorer up -d

develop-deploy:
  extends: .deploy
  environment:
    name: develop
    url: https://656-echo-explorer.pixelplex-test.by
  only:
    - develop
  tags:
    - pp-new-develop

stage-deploy:
  extends: .deploy
  environment:
    name: master
    url: http://656-echo-explorer.pixelplexlabs.com
  only:
    - master
  tags:
    - pp-stage

production-deploy:
  extends: .deploy
  environment:
    name: prod
    url: https://explorer.echo-dev.io
  only:
    - tags
  tags:
    - echo-explorer-1
