import { OPERATIONS_IDS } from 'echojs-lib';

import transformSidechainOperations from './specifics.ops/sidechain';

export const transformOperationDataByType = async (opNumber, data) => {
	switch (opNumber) {
		case OPERATIONS_IDS.SIDECHAIN_ETH_CREATE_ADDRESS:
		case OPERATIONS_IDS.SIDECHAIN_ETH_APPROVE_ADDRESS:
		case OPERATIONS_IDS.SIDECHAIN_ETH_DEPOSIT:
		case OPERATIONS_IDS.SIDECHAIN_ETH_SEND_DEPOSIT:
		case OPERATIONS_IDS.SIDECHAIN_ETH_WITHDRAW:
		case OPERATIONS_IDS.SIDECHAIN_ETH_SEND_WITHDRAW:
		case OPERATIONS_IDS.SIDECHAIN_ETH_APPROVE_WITHDRAW:
		case OPERATIONS_IDS.SIDECHAIN_ETH_UPDATE_CONTRACT_ADDRESS:
		case OPERATIONS_IDS.SIDECHAIN_ISSUE:
		case OPERATIONS_IDS.SIDECHAIN_BURN:
		case OPERATIONS_IDS.SIDECHAIN_ERC20_REGISTER_TOKEN:
		case OPERATIONS_IDS.SIDECHAIN_ERC20_DEPOSIT_TOKEN:
		case OPERATIONS_IDS.SIDECHAIN_ERC20_SEND_DEPOSIT_TOKEN:
		case OPERATIONS_IDS.SIDECHAIN_ERC20_WITHDRAW_TOKEN:
		case OPERATIONS_IDS.SIDECHAIN_ERC20_SEND_WITHDRAW_TOKEN:
			return transformSidechainOperations(opNumber, data);
		default:
			return {};
	}
};
