export const DEFAULT_TABLE_LENGTH = 50;

export const DEFAULT_LOAD_MORE_TITLE = 'Load more';

export const LOAD_MORE_TEMPLATE = {
	BLOCK_TABLE: `${DEFAULT_LOAD_MORE_TITLE} blocks`,
	BLOCK_INFORMATION: DEFAULT_LOAD_MORE_TITLE,
};
