import { constants } from 'echojs-lib';

export const ACCOUNT_OBJECT_PREFIX = `1.${constants.PROTOCOL_OBJECT_TYPE_ID.ACCOUNT}`;
export const ASSET_OBJECT_PREFIX = `1.${constants.PROTOCOL_OBJECT_TYPE_ID.ASSET}`;
export const CONTRACT_OBJECT_PREFIX = `1.${constants.PROTOCOL_OBJECT_TYPE_ID.CONTRACT}`;
export const OPERATION_HISTORY_OBJECT_PREFIX = `1.${constants.PROTOCOL_OBJECT_TYPE_ID.OPERATION_HISTORY}`;
