export const OPERATION_TYPES = {
	TRANSFER: 'Transfer',
	TRANSFER_TO_ADDRESS: 'Transfer to address',
	OVERRIDE_TRANSFER: 'Override transfer',
	ACCOUNT_CREATE: 'Create account',
	CONTRACT_TRANSFER: 'Contract transfer',
	ACCOUNT_UPDATE: 'Update account',
	ACCOUNT_WHITELIST: 'Account whitelist',
	ACCOUNT_ADDRESS_CREATE: 'Account address create',
	ASSET_CREATE: 'Create asset',
	ASSET_UPDATE: 'Update asset',
	ASSET_UPDATE_BITASSET: 'Update SmartCoin',
	ASSET_UPDATE_FEED_PRODUCERS: 'Update asset feed producers',
	ASSET_ISSUE: 'Issue asset',
	ASSET_REVERSE: 'Burn asset',
	ASSET_FUND_FEE_POOL: 'Fund asset fee pool',
	ASSET_PUBLISH_FEED: 'Publish feed',
	ASSET_CLAIM_FEES: 'Claim asset fees',
	PROPOSAL_CREATE: 'Create proposal',
	PROPOSAL_UPDATE: 'Update proposal',
	PROPOSAL_DELETE: 'Delete proposal',
	COMMITTEE_MEMBER_CREATE: 'Create committee member',
	COMMITTEE_MEMBER_UPDATE: 'Update committee member',
	COMMITTEE_MEMBER_UPDATE_GLOBAL_PARAMETERS: 'Global parameters update',
	COMMITTEE_MEMBER_ACTIVATE: 'Activate committee member',
	COMMITTEE_MEMBER_DEACTIVATE: 'Deactivate committee member',
	COMMITTEE_FROZEN_BALANCE_DEPOSIT: 'Committee frozen balance deposit',
	COMMITTEE_FROZEN_BALANCE_WITHDRAW: 'Committee frozen balance withdraw',
	VESTING_BALANCE_CREATE: 'Create vesting balance',
	VESTING_BALANCE_WITHDRAW: 'Withdraw vesting balance',
	BALANCE_CLAIM: 'Claim balance',
	BALANCE_FREEZE: 'Balance freeze',
	BALANCE_UNFREEZE: 'Balance unfreeze',
	CONTRACT_CREATE: 'Contract create',
	CONTRACT_CALL: 'Contract call',
	CONTRACT_INTERNAL_CREATE: 'Contract internal create',
	CONTRACT_INTERNAL_CALL: 'Contract internal call',
	CONTRACT_SELFDESTRUCT: 'Contract selfdestruct',
	CONTRACT_UPDATE: 'Contract update',
	CONTRACT_FUND_POOL: 'Contract fund pool',
	CONTRACT_WHITELIST: 'Contract whitelist',
	SIDECHAIN_ETH_CREATE_ADDRESS: 'Create eth address',
	SIDECHAIN_ETH_APPROVE_ADDRESS: 'Approve eth address',
	SIDECHAIN_ETH_DEPOSIT: 'Deposit eth',
};
