export const OPERATION_TYPES = {
	TRANSFER: 'Transfer',
	TRANSFER_TO_ADDRESS: 'Transfer to address',
	OVERRIDE_TRANSFER: 'Override transfer',
	ACCOUNT_CREATE: 'Create account',
	CONTRACT_TRANSFER: 'Contract transfer',
	ACCOUNT_UPDATE: 'Update account',
	ACCOUNT_WHITELIST: 'Account whitelist',
	ACCOUNT_ADDRESS_CREATE: 'Account address create',
	ASSET_CREATE: 'Create asset',
	ASSET_UPDATE: 'Update asset',
	ASSET_UPDATE_BITASSET: 'Update SmartCoin',
	ASSET_UPDATE_FEED_PRODUCERS: 'Update asset feed producers',
	ASSET_ISSUE: 'Issue asset',
	ASSET_REVERSE: 'Burn asset',
	ASSET_FUND_FEE_POOL: 'Fund asset fee pool',
	ASSET_PUBLISH_FEED: 'Publish feed',
	ASSET_CLAIM_FEES: 'Claim asset fees',
	PROPOSAL_CREATE: 'Create proposal',
	PROPOSAL_UPDATE: 'Update proposal',
	PROPOSAL_DELETE: 'Delete proposal',
	COMMITTEE_MEMBER_CREATE: 'Create committee member',
	COMMITTEE_MEMBER_UPDATE: 'Update committee member',
	COMMITTEE_MEMBER_UPDATE_GLOBAL_PARAMETERS: 'Global parameters update',
};
